language: rust

rust:
  - stable

env:
# We want to see a call stack if something has failed to examine
# what happened, so set `RUST_BACKTRACE`:
  - RUST_BACKTRACE=1
  
before_script:
# We want to check for any warnings and errors in this crate, so
# install Clippy:
  - rustup component add clippy

script:
  - cargo build --all --verbose

# Let Clippy also check the tests and non-default crate features
# to ensure that the code is correct:
  - cargo clippy --all --all-targets --all-features
  - sudo env PATH=$PATH cargo test --all
