language: rust

rust:
  - nightly
  - beta
  - stable

env:
  - RUST_BACKTRACE=1

before_script:
  - rustup component add clippy

script:
  - cargo build --all --verbose
  - cargo clippy --all
  - cargo test --all