language: rust

rust:
  - stable

# We want to see a call stack if something has failed to examine
# what happened, so set `RUST_BACKTRACE`
env:
  - RUST_BACKTRACE=1
  
before_script:
# We want to check for any warnings and errors in this crate, so
# install Clippy:
  - rustup component add clippy
  
# Anevicon uses raw IPv4/IPv6 sockets that require root permissions,
# so add cargo to the PATH environmental variable
  - sudo PATH+=":/home/gymmasssorla/.cargo/bin/cargo"

script:
  - cargo build --all --verbose

# Let Clippy also check the tests and non-default crate features
# to ensure that the code is correct
  - cargo clippy --all --all-targets --all-features
  - sudo cargo test --all
